on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: '.'
    - name: "Zip Firmware Files"
      run: VERSION="snapshot" BUILD="github-main" sh contrib/dist.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: |
          JellingStone*.zip
    - name: "Create Release"
      uses: "marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1"
      with:
        automatic_release_tag: "current-main"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          JellingStone*.zip
    - name: "Upload files to webdav.fieldtracks.org"
      uses: "bxb100/action-upload-webdav@d19f1edf785abf4b0b7f818ba46b6dba9b0334c6"
      with:
        webdav_address: https://webdav.fieldtracks.org
        webdav_username: ${{secrets.webdav_username}}
        webdav_password: ${{secrets.webdav_password}}
        webdav_upload_path: "/JellingStone"
        files: "JellingStone*.zip"
