on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: '.'
    - name: "Zip Firmware Files"
      run: BUILD="gh-${{ env.GITHUB_RUN_ID }}" contrib/dist.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: |
          JellingStone*.zip
    - name: "Create Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "current-main"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          JellingStone*.zip

