on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v4.4
        target: esp32
        path: '.'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Firmware
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/JellingStone.bin
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      name: 'Delete old releases (keep latest: 2)'
      with:
        keep_latest: 2
        delete_tag_pattern: snapshot # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Create Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: "current-dev"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/JellingStone.bin      

